# Generated by Django 4.1.5 on 2023-01-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='member',
            field=models.CharField(max_length=32),
        ),
    ]
