# Generated by Django 4.1.5 on 2023-01-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='name',
            field=models.CharField(default='HoHo', max_length=32),
        ),
    ]
