# Generated by Django 4.1.5 on 2023-01-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeons', '0002_party_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='member',
        ),
        migrations.AlterField(
            model_name='party',
            name='name',
            field=models.CharField(default='Party', max_length=32),
        ),
    ]
