# Generated by Django 4.1.5 on 2023-01-17 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_article_reporter_delete_party_article_reporter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Reporter',
        ),
    ]
