# Generated by Django 4.1.5 on 2023-01-09 08:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='avatars')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_type', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Gear', max_length=32)),
                ('weapon', models.CharField(default='Sling', max_length=16)),
                ('armor', models.CharField(default='Shirt', max_length=16)),
                ('misc', models.CharField(default='Amulet', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('email', models.EmailField(default='email@email.com', max_length=64)),
                ('created', models.DateTimeField(default=datetime.datetime(2023, 1, 9, 10, 52, 45, 650795))),
                ('avatar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create.avatar')),
                ('character_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create.characterclass')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create.gear')),
            ],
        ),
    ]
