# Generated by Django 4.1.5 on 2023-01-11 09:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0002_alter_avatar_avatar_alter_hero_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 11, 11, 28, 31, 912558)),
        ),
    ]
