# Generated by Django 4.1.5 on 2023-01-12 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0004_delete_characterclass_delete_gear_alter_hero_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 12, 19, 46, 28, 987825)),
        ),
    ]
