# Generated by Django 4.1.5 on 2023-01-19 21:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0006_alter_hero_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Party', max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='hero',
            name='party_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hero',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 19, 23, 0, 26, 314820)),
        ),
        migrations.AddField(
            model_name='hero',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='create.party'),
        ),
    ]
