# Generated by Django 4.1.5 on 2023-01-17 10:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dungeons', '0003_remove_party_member_alter_party_name'),
        ('create', '0012_alter_hero_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dungeons.party'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 17, 12, 9, 30, 737759)),
        ),
    ]
