# Generated by Django 4.1.5 on 2023-01-18 09:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0019_alter_hero_created_alter_hero_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='party_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hero',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 18, 11, 31, 43, 532349)),
        ),
    ]
