# Generated by Django 4.1.5 on 2023-01-19 09:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0020_hero_party_member_alter_hero_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 19, 11, 42, 18, 410198)),
        ),
    ]
